### ISSUE TITLE
change name?

### ISSUE THREAD

**Issue by pbellec** [brainsprite/brainsprite.py#4]
brainsprite.py would make much more sense than spritipy. spritipy sounds like THE library to make sprites in python. It's not. Also, spritipy will have api to generate stand-alone brainsprite viz, or inject them into a notebook. This is inconsistent with the name spritipy, but follows directly from the name brainsprite.py.

I don't think anybody is using that code base (there is hardly anything in it yet), and anyway this repo is still new and has not been advertised anywhere. It is not too late...

**Comment by surchs** [comment]
I'm fine with changing the name for these reasons. But I would go for something without a file ending. I would also keep it separate from the core visualization library in name as that may be confusing. We could go for brainslicer or something like that.

**Comment by pbellec** [comment]
would you mind elaborating what is the problem with file ending?

Also brainsprite.py is set to be a python API for brainsprite.js. 
  What do you think will be confusing for users?

**Comment by surchs** [comment]
I think someone who comes to the organisation page and sees brainsprite.js and brainsprite.py will assume that they are different implementations of the same thing or at the very least won't know which one does what.

I don't like the dot in the repo name because that's a reserved character to delimit python modules and name spaces. And it otherwise makes the repo and the default named local copy look like a file name.

I think it'd be clearer to use a name that is descriptive of what the package does rather than the language it's written in. But if the language is to be part of the name, I'd prefer a dash over a dot

**Comment by pbellec** [comment]
revisiting this issue.

First users would be right to assume they are different implementations of the same thing, because that's exactly what that is.

Second, it is very common to use .js extension in packages names.
  If I look at plotly, they have plotly.js (their core javascript library), and then plotly.py and plotly.r (python and R APIs respectively).
    
Of course the name of the pyhon's library would be brainsprite, and not brainsprite.py. The extension .py would only be used in the name of the python repo. And incidently, would also be the name of the library file, i.e. /brainsprite/brainsprite.py in the brainsprite.py repository.

I believe this is easy to understand and actually avoids confusion: why have a different project name for a simple API?

**Comment by pbellec** [comment]
alright, brainsprite.py it is.
